@startuml
title Diagrama de Casos de Uso - Atlas Contábil

left to right direction

actor "Contador" as Usuario

rectangle "Atlas Contábil" {

  (Realizar Login) as UC1
  (Visualizar Dashboard) as UC2
  (Visualizar Lista de Clientes) as UC3
  (Consultar Detalhes do Cliente) as UC4
  (Simular Cenário Tributário) as UC5
  (Visualizar Modo Estratégico) as UC6

}

Usuario --> UC1
Usuario --> UC2
Usuario --> UC3
Usuario --> UC4
Usuario --> UC5
Usuario --> UC6

UC4 --> UC5 : <<include>>

@enduml
